name: "pnpm-outdated-to-datadog"
description: "Github action to send metrics on outdated dependencies to datadog"
inputs:
  datadog-api-key:
    required: true
  github-token:
    required: true
  datadog-repo-name:
    required: false
    default: ${{ github.repository }}
  working-directory:
    required: false
    default: .
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: pnpm/action-setup@v4
      with:
        run_install: true
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - run: pnpm outdated --json | node ${GITHUB_ACTION_PATH}/calcOutdatedMetrics.js | ${GITHUB_ACTION_PATH}/shipMetrics.sh
      shell: bash {0}
      working-directory: ${{ inputs.working-directory }}
      env:
        DATADOG_API_KEY: ${{ inputs.datadog-api-key }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DATADOG_REPO_NAME: ${{ inputs.datadog-repo-name }}
